[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    "__version__.py",
    "pyproject.toml:version",
    "docker-compose.yml:image:fcs:$version",
    "docker-compose-buildx.yml:tags:registry:5000/fcs/fcs:$version",
    "docker-compose-buildx.yml:image:registry:5000/fcs/fcs:$version"
]
