repos:
- hooks:
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-ast
  - id: check-merge-conflict
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
- hooks:
  - id: black
    language_version: python3.12
  repo: https://github.com/psf/black
  rev: 25.1.0
- hooks:
  - additional_dependencies:
    - black==25.1.0
    id: blacken-docs
  repo: https://github.com/adamchainz/blacken-docs
  rev: 1.19.1
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.1.1
