[project]
name = "FeedCopterSpotter"
version = "0.1.1"

[tool.commitizen]
version_provider = "pep621"
version_files = [
    "pyproject.toml:version",
    "fcs/__init__.py:__version__"
]
update_changelog_on_bump = true
