[project]
name = "FeedCopterSpotter"
version = "0.1.5"

[tool.commitizen]
version_provider = "pep621"
version_files = [
    "pyproject.toml:version",
    "docker-compose.yml:image:fcs:$version",
    "docker-compose-buildx.yml:tags:registry:5000/fcs/fcs:$version",
    "docker-compose-buildx.yml:image:registry:5000/fcs/fcs:$version"
]
update_changelog_on_bump = true
