apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ./kube-docker-compose.yml_kube_ignore -n fcs convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: feed-copterspotter
  name: feed-copterspotter
  namespace: fcs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: feed-copterspotter
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ./kube-docker-compose.yml_kube_ignore -n fcs convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: feed-copterspotter
    spec:
      containers:
        - args:
            - python3
            - feed_copterspotter.py
            - -i
            - "15"
            - -w
            - -v
          env:
            - name: FEEDER_ID
              valueFrom:
                configMapKeyRef:
                  key: FEEDER_ID
                  name: env
            - name: MONGOPW
              valueFrom:
                configMapKeyRef:
                  key: MONGOPW
                  name: env
            - name: MONGOUSER
              valueFrom:
                configMapKeyRef:
                  key: MONGOUSER
                  name: env
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URL
                  name: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: env
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: SERVER
              valueFrom:
                configMapKeyRef:
                  key: SERVER
                  name: env
          image: registry:5000/fcs/feed_copterspotter:20250119-02
          name: feed-copterspotter
          ports:
            - containerPort: 8999
              protocol: TCP
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      restartPolicy: Always

      tolerations:
        - key: "arm64"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "asdb"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
